### ISSUE TITLE
When i installed this theme i got a lot of error 

### ISSUE THREAD

**Issue by hasanmallick** [mybbgroup/CurvesUI#7]
Can anyone help me install this theme clearly

**Comment by MattyWjeisz** [comment]
You need to explain what errors you’re receiving.

**Comment by effone** [comment]
More info required. Closing.

**Comment by hasanmallick** [comment]
Check errors forums.likebd.com

**Comment by MattyWjeisz** [comment]
You have not followed the installation instructions correctly. Please read the README file included in the latest download package and follow ALL instructions correctly.
